<?php
class PhyMoji {
  private $data;
  
  function __construct() {
    $this->data = array(
        "primates" => "🐒",
        "haplorhini" => "🐒",
        "gorilla" => "🦍",
        "hominidae" => "🦧",
        "canidae" => "🐺",
        "carnivora" => "🐺",
        "canis familiaris" => "🐕",
        "vulpes" => "🦊",
        "procyonidae" => "🦝",
        "felis" => "🐈",
        "felidae" => "🐆",
        "panthera" => "🦁",
        "panthera leo" => "🦁",
        "panthera tigris" => "🐅",
        "panthera pardus" => "🐆",
        "equus ferus" => "🐎",
        "equus grevyi" => "🦓",
        "equus quagga" => "🦓",
        "equus zebra" => "🦓",
        "equidae" => "🐎",
        "hippotigris" => "🦓",
        "perissodactyla" => "🐎",
        "cervidae" => "🦌",
        "artiodactyla" => "🦌",
        "bison" => "🦬",
        "bos taurus" => "🐄",
        "bovidae" => "🐄",
        "bubalus" => "🐃",
        "sus domesticus" => "🐖",
        "suidae" => "🐗",
        "caprinae" => "🐏",
        "ovis" => "🐏",
        "capra" => "🐐",
        "camelus bactrianus" => "🐫",
        "camelidae" => "🐪",
        "lama" => "🦙",
        "giraffidae" => "🦒",
        "proboscidea" => "🐘",
        "mammuthus" => "🦣",
        "rhinocerotidae" => "🦏",
        "hippopotamidae" => "🦛",
        "rodentia" => "🐁",
        "mus" => "🐁",
        "rattus" => "🐀",
        "cricetidae" => "🐹",
        "lagomorpha" => "🐇",
        "sciuridae" => "🐿️",
        "castoridae" => "🦫",
        "eulipotyphla" => "🦔",
        "chiroptera" => "🦇",
        "ursidae" => "🐻",
        "ursus maritimus" => "🐻‍❄️",
        "phascolarctos" => "🐨",
        "marsupialia" => "🦘",
        "ailuropoda" => "🐼",
        "pilosa" => "🦥",
        "lutrinae" => "🦦",
        "mustelidae" => "🦨",
        "mephitidae" => "🦨",
        "meles" => "🦡",
        "galliformes" => "🦃",
        "gallus" => "🐓",
        "aves" => "🐦",
        "sphenisciformes" => "🐧",
        "columbiformes" => "🕊️",
        "accipitriformes" => "🦅",
        "anseriformes" => "🦆",
        "cygnus" => "🦢",
        "strigiformes" => "🦉",
        "raphinae" => "🦤",
        "phoenicopteridae" => "🦩",
        "pavoninae" => "🦚",
        "psittaciformes" => "🦜",
        "amphibia" => "🐸",
        "crocodilia" => "🐊",
        "testudines" => "🐢",
        "reptilia" => "🦎",
        "serpentes" => "🐍",
        "sauropoda" => "🦕",
        "dinosauria" => "🦖",
        "cetacea" => "🐋",
        "delphinidae" => "🐬",
        "pinnipedia" => "🦭",
        "osteichthyes" => "🐟",
        "pterophyllum" => "🐠",
        "tetraodontidae" => "🐡",
        "chondrichthyes" => "🦈",
        "cephalopoda" => "🐙",
        "anthozoa" => "🪸",
        "mollusca" => "🐌",
        "lepidoptera" => "🦋",
        "arthropoda" => "🐛",
        "formicidae" => "🐜",
        "hymenoptera" => "🐝",
        "coleoptera" => "🪲",
        "coccinellidae" => "🐞",
        "orthoptera" => "🦗",
        "blattodea" => "🪳",
        "arachnida" => "🕷️",
        "scorpiones" => "🦂",
        "diptera" => "🪰",
        "annelida" => "🪱",
        "culicoidea" => "🦟",
        "bacteria" => "🦠",
        "prunus" => "🌸",
        "nelumbonaceae" => "🪷",
        "rosales" => "🌹",
        "plantae" => "🌱",
        "coleoidea" => "🦑",
        "crustacea" => "🦐",
        "nephropidae" => "🦞",
        "brachyura" => "🦀",
        "fagaceae" => "🌰",
        "fungi" => "🍄",
        "acer" => "🍁",
        "fabaceae" => "🍀",
        "trifolium" => "☘️",
        "poales" => "🌾",
        "cactaceae" => "🌵",
        "arecaceae" => "🌴",
        "pinales" => "🌲",
        "liliales" => "🌷",
        "asterales" => "🌻",
        "malvales" => "🌺",
        "vitaceae" => "🍇",
        "cucurbitaceae" => "🍈",
        "rutaceae" => "🍊",
        "faboideae" => "🥜",
        "allioideae" => "🧅",
        "allium sativum" => "🧄",
        "brassicales" => "🥦",
        "cucumis" => "🥒",
        "capsicum" => "🌶️",
        "zea" => "🌽",
        "apiaceae" => "🥕",
        "solanum tuberosum" => "🥔",
        "solanum melongena" => "🍆",
        "laurales" => "🥑",
        "cocos" => "🥥",
        "lamiales" => "🫒",
        "solanales" => "🍅",
        "actinidiaceae" =>"🥝",
        "ericales" => "🫐",
        "fragaria" => "🍓",
        "prunus persicus" =>"🍑",
        "pyrus" => "🍐",
        "maleae" => "🍎",
        "sapindales" => "🥭",
        "bromeliaceae" => "🍍",
        "zingiberales" => "🍌"
    );
}

    public function phymoji($names) {
        foreach ($names as $name) {
            if (array_key_exists($name, $this->data)) {
                $ret = array(
                "emoji" => $this->data[$name],
                "match" => $name
            );
            return($ret);
            }
        }
        return(array("emoji" => "", "match"=>""));
    }

    public function getTaxon($e) {
        foreach ($this->data as $taxon => $emoji) {
            if ($e == $emoji) {return($taxon);}
        }
    }
}
